name: Json2V quality code CI

concurrency:
  group: ci-${{ github.event.number }}
  cancel-in-progress: true

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  fmt-check:
    runs-on: ubuntu-22.04

    steps:
      - name: Setup V
        uses: vlang/setup-v@v1.3
        with:
          check-latest: true

      - uses: actions/checkout@v3

      - name: Execute Tests
        run: ls

      - name: V doctor
        run: v doctor

      - name: Verify Fmt
        run: v fmt -verify .

  run-tests:
    runs-on: ubuntu-22.04

    steps:
      - name: Setup V
        uses: vlang/setup-v@v1.3
        with:
          check-latest: true

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: V doctor
        run: v doctor

      - name: Execute Tests
        run: v -cc tcc -stats test ~/.
